#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Nathan M. Fraske
#
# Stop hook -- WSL-EPHEMERAL STATE POLICY enforcement (owner directive 2026-06-12).
#
# Every session end: regenerate the agent handoff + snapshot durable agent memory,
# then COMMIT + PUSH both to the dedicated `ops/agent-handoff` branch on the remote.
# This guarantees the handoff can never again exist only on the (ephemeral) WSL
# volume -- the failure that lost the prior session's handoff in the 2026-06-12 wipe.
#
# It is NON-DISRUPTIVE BY CONSTRUCTION: it never checks out, never touches HEAD or the
# normal index. The commit is assembled with git plumbing (hash-object -> a temp index ->
# commit-tree) and pushed straight to the branch ref. The ONLY working-tree write is
# refreshing the agent's own durable memory mirror (.claude/memory/*.md, already git-tracked
# and meant to be committed) from the live ~/.claude memory, so the in-tree handoff never
# drifts stale -- the start hook seeds the live dir back from it after a WSL wipe.
# Fail-soft + time-bounded: a Stop hook must never block or fail the session.
set -uo pipefail
exec 2>/dev/null            # never leak noise onto the session's Stop path
cat >/dev/null || true      # drain the hook JSON on stdin; we don't need it

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
BRANCH="ops/agent-handoff"
cd "$ROOT" 2>/dev/null || exit 0
git rev-parse --git-dir >/dev/null 2>&1 || exit 0   # not a git repo -> nothing to do

# Resolve the persistent-memory dir (same derivation as session-start.sh).
memdir="$HOME/.claude/projects/$(echo "$ROOT" | tr '/.' '--')/memory"
[ -d "$memdir" ] || memdir="$HOME/.claude/projects/-home-nathan-CEC-Platform/memory"

# --- refresh the DURABLE in-tree memory mirror (WSL-ephemeral state policy) ----------
# Mirror the live ~/.claude memory *.md into the committed, git-tracked .claude/memory/
# so the versioned handoff stays current (it had drifted stale -- the live handoff was
# 8 KB while the committed copy was 2 KB). Plain file copy: no HEAD/index touch; the next
# normal commit carries them. The off-tree side-branch push below is the wipe-proof copy;
# this in-tree mirror is what the start hook seeds from on a fresh clone.
committed="$ROOT/.claude/memory"
if [ -d "$memdir" ] && [ -d "$committed" ]; then
  for f in "$memdir"/*.md; do
    [ -e "$f" ] || continue
    dst="$committed/$(basename "$f")"
    # NEWEST-WINS (FOLLOWUPS 2026-07-17, bit twice): after a merge the REPO copy
    # can be fresher than the live memory dir -- an unconditional cp here clobbered
    # the merged handoff with a stale pre-merge copy. Only mirror live->committed
    # when the live file is strictly newer; the start hook covers committed->live.
    if [ ! -e "$dst" ] || [ "$f" -nt "$dst" ]; then
      cp "$f" "$dst" 2>/dev/null || true
    fi
  done
fi

# Pull in the survives-WSL bot PAT if present (else fall back to the gh credential).
# shellcheck disable=SC1091
[ -f "$ROOT/ops/secrets/load-secrets.sh" ] && . "$ROOT/ops/secrets/load-secrets.sh" 2>/dev/null || true

run() { timeout 60 "$@"; }   # hard cap; the session never waits on git/network

# --- 1) generate the handoff into a TEMP file (never written to the working tree) ---
tmp_handoff="$(mktemp)"; trap 'rm -f "$tmp_handoff"' EXIT
{
  echo "# Agent handoff — $(date -u '+%Y-%m-%d %H:%M:%SZ')"
  echo
  echo "_Auto-generated by .claude/hooks/session-end.sh and pushed to \`$BRANCH\`._"
  echo "_Per the WSL-ephemeral state policy: this is the durable, remote copy._"
  echo
  echo "## Repo state"
  echo '```'
  echo "branch:  $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
  echo "HEAD:    $(git log -1 --oneline 2>/dev/null)"
  echo "status:  $(git status --porcelain 2>/dev/null | wc -l) uncommitted path(s)"
  echo '```'
  echo
  echo "### Recent commits"
  echo '```'
  git log --oneline -12 2>/dev/null
  echo '```'
  echo
  echo "### Working-tree changes"
  echo '```'
  git status --short 2>/dev/null | head -40
  echo '```'
  echo
  echo "## Broker"
  if curl -fsS --max-time 3 "http://localhost:${CEC_BROKER_PORT:-8080}/broker/stats" 2>/dev/null; then :; else
    echo "(broker not reachable on :${CEC_BROKER_PORT:-8080})"
  fi
  echo
  echo "## Persistent memory snapshot"
  if [ -f "$memdir/current-work-handoff.md" ]; then
    echo "### current-work-handoff.md"; echo; cat "$memdir/current-work-handoff.md"
  fi
  if [ -f "$memdir/MEMORY.md" ]; then
    echo; echo "### MEMORY.md (index)"; echo; cat "$memdir/MEMORY.md"
  fi
} > "$tmp_handoff"

# --- 2) assemble a commit with plumbing, on top of the remote branch (no checkout) ---
run git fetch -q origin "$BRANCH" 2>/dev/null || true
tmpidx="$(mktemp)"; export GIT_INDEX_FILE="$tmpidx"
trap 'rm -f "$tmp_handoff" "$tmpidx"' EXIT
parent="$(git rev-parse -q --verify "refs/remotes/origin/$BRANCH" 2>/dev/null || true)"
if [ -n "$parent" ]; then git read-tree "$parent" 2>/dev/null || git read-tree --empty
else git read-tree --empty; fi

add_blob() {  # add_blob <src-file> <path-in-tree>
  [ -f "$1" ] || return 0
  local blob; blob="$(git hash-object -w "$1" 2>/dev/null)" || return 0
  git update-index --add --cacheinfo "100644,$blob,$2" 2>/dev/null || true
}
add_blob "$tmp_handoff" "docs/agent/handoff.md"
for f in "$memdir"/*.md; do
  [ -e "$f" ] || continue
  add_blob "$f" ".claude/memory/$(basename "$f")"
done

tree="$(git write-tree 2>/dev/null)" || exit 0
[ -n "$tree" ] || exit 0
# Skip an empty no-op commit if nothing changed vs the parent.
if [ -n "$parent" ] && [ "$tree" = "$(git rev-parse "$parent^{tree}" 2>/dev/null)" ]; then exit 0; fi
msg="agent handoff $(date -u '+%Y-%m-%dT%H:%M:%SZ') [session-end hook]"
if [ -n "$parent" ]; then commit="$(git commit-tree "$tree" -p "$parent" -m "$msg" 2>/dev/null)"
else commit="$(git commit-tree "$tree" -m "$msg" 2>/dev/null)"; fi
[ -n "$commit" ] || exit 0

# --- 3) push to the branch ref. Prefer the survives-WSL PAT; fall back to gh creds. ---
unset GIT_INDEX_FILE
if [ -n "${CEC_BOT_PAT:-}" ]; then
  url="$(git remote get-url origin | sed -E "s#https://([^@/]*@)?github.com#https://x-access-token:${CEC_BOT_PAT}@github.com#")"
  run git push -q "$url" "$commit:refs/heads/$BRANCH" 2>/dev/null || true
else
  run git push -q origin "$commit:refs/heads/$BRANCH" 2>/dev/null || true
fi

# --- 4) ring-buffer housekeeping (owner ask 2026-07-18): trim the disposable
# working dirs (repo build/, agent project sessions, agent job tmp) so they
# never balloon. Fail-soft + time-capped; runs AFTER the durable push so
# cleanup can never delay or break the handoff.
timeout 120 python3 "$ROOT/scripts/cec_housekeep.py" --quiet >/dev/null 2>&1 || true
exit 0
