#!/usr/bin/env python3
"""FABRICABILITY CHECK -- would a fab house actually build this board?

Owner directive 2026-07-27: "if something is fabbable in our router, it is
actually doable in a fab house and it doesn't have artifacts from automated
routing and placement that would prevent that."

Our DRC answers a DIFFERENT question: it checks a board against ITS OWN
`.kicad_pro` / `.kicad_dru`. Two ways that misleads, both measured on this repo:

  * the rules may not travel -- candidate/ dirs carry no `.kicad_dru`, so the
    hub read 5 violations there against 20 with its rules present;
  * the rules may not exist -- boards here set `min_clearance: 0.0` and
    `min_silk_clearance: 0.0`, so there is NO global floor at all; anything not
    covered by a netclass is simply unchecked.

So this re-runs the check against a FAB PROFILE (a vendor's real capability
limits) rather than our intent, using KiCad's own geometry engine so clearance
math is not reimplemented here -- then adds the artifact classes DRC does not
model at all: pour slivers, isolated copper islands, and acute-angle acid traps.

Usage:
    python3 scripts/cec_fab_check.py BOARD [BOARD ...] [--profile jlcpcb]
                                     [--copper-oz 2] [--json OUT]

Exit code 1 if any board has a fab-blocking finding, else 0.
"""

import argparse
import collections
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

# --------------------------------------------------------------------------
# FAB PROFILES -- a vendor's stated capability, NOT our design intent.
# JLCPCB standard process (the repo's fab -- BOM outputs are *-jlcpcb.csv).
# Values are the vendor's published minimums; where a value depends on copper
# weight, the 2oz entry is used for outer layers on the cable boards, which is
# the binding case (heavier copper needs wider spacing because of etch
# undercut).
# --------------------------------------------------------------------------
PROFILES = {
    "jlcpcb": {
        "name": "JLCPCB standard process",
        "min_track_1oz": 0.127,      # 5 mil
        "min_track_2oz": 0.20,       # heavier copper etches wider
        "min_clearance_1oz": 0.127,
        "min_clearance_2oz": 0.20,
        "min_annular": 0.13,
        "min_drill": 0.20,
        "min_via_diameter": 0.45,
        "min_hole_to_hole": 0.50,    # different nets, centre-to-centre edge gap
        "min_copper_edge": 0.20,
        "min_silk_width": 0.15,
        "min_sliver": 0.10,          # copper/mask sliver a process can hold
    },
}


def profile_rules(prof, copper_oz):
    """The binding numbers for this copper weight."""
    k = "2oz" if copper_oz >= 2 else "1oz"
    return {
        "track": prof["min_track_%s" % k],
        "clearance": prof["min_clearance_%s" % k],
        "annular": prof["min_annular"],
        "drill": prof["min_drill"],
        "via": prof["min_via_diameter"],
        "h2h": prof["min_hole_to_hole"],
        "edge": prof["min_copper_edge"],
        "silk": prof["min_silk_width"],
        "sliver": prof["min_sliver"],
    }


def write_fab_dru(path, r):
    """A .kicad_dru encoding the FAB's limits, not ours."""
    with open(path, "w") as fh:
        fh.write(
            "(version 1)\n"
            "# GENERATED by cec_fab_check -- a FAB HOUSE capability profile.\n"
            "# This deliberately replaces the board's own intent rules: the\n"
            "# question here is not 'does it meet our spec' but 'can it be\n"
            "# built'. Do not commit this beside a board.\n"
            '(rule "fab min track"\n'
            "\t(constraint track_width (min %smm)))\n"
            '(rule "fab min clearance"\n'
            "\t(constraint clearance (min %smm)))\n"
            '(rule "fab min annular"\n'
            "\t(constraint annular_width (min %smm)))\n"
            '(rule "fab min drill"\n'
            "\t(constraint hole_size (min %smm)))\n"
            '(rule "fab hole to hole"\n'
            "\t(constraint hole_to_hole (min %smm)))\n"
            '(rule "fab copper to edge"\n'
            "\t(constraint edge_clearance (min %smm)))\n"
            '(rule "fab silk width"\n'
            "\t(constraint text_thickness (min %smm)))\n"
            % (r["track"], r["clearance"], r["annular"], r["drill"],
               r["h2h"], r["edge"], r["silk"]))


def run_fab_drc(board_path, r):
    """KiCad's own geometry engine, against the fab profile."""
    work = tempfile.mkdtemp(prefix="fabchk-")
    try:
        base = os.path.join(work, "b")
        shutil.copyfile(board_path, base + ".kicad_pcb")
        pro = os.path.splitext(board_path)[0] + ".kicad_pro"
        if os.path.exists(pro):
            shutil.copyfile(pro, base + ".kicad_pro")
        write_fab_dru(base + ".kicad_dru", r)
        out = os.path.join(work, "drc.json")
        subprocess.run(
            ["kicad-cli", "pcb", "drc", "--severity-error", "--format", "json",
             "-o", out, base + ".kicad_pcb"],
            capture_output=True, text=True, timeout=900)
        if not os.path.exists(out):
            return None, None
        d = json.load(open(out))
        return d.get("violations") or [], d.get("unconnected_items") or []
    finally:
        shutil.rmtree(work, ignore_errors=True)


def artifact_scan(board_path, r):
    """The classes DRC does not model: slivers, islands, acid traps.

    These are the automated-routing/placement leftovers the owner named -- a
    pour can be DRC-legal and still contain a 40um neck the etch will not hold,
    and an island of copper connected to nothing is a plating and shorting
    hazard even though no rule forbids it.
    """
    import pcbnew
    from shapely.geometry import Polygon, box as _box, LineString
    from shapely.ops import unary_union
    b = pcbnew.LoadBoard(board_path)
    out = {"slivers": [], "islands": [], "acid_traps": []}

    # --- pour slivers + isolated islands, per zone per layer
    for z in b.Zones():
        if z.GetIsRuleArea():
            continue
        net = z.GetNetname()
        nm = z.GetZoneName() or "?"
        for lid in b.GetEnabledLayers().CuStack():
            if not z.IsOnLayer(lid):
                continue
            try:
                src = z.GetFilledPolysList(lid)
            except Exception:                              # noqa: BLE001
                continue
            for i in range(src.OutlineCount()):
                o = src.Outline(i)
                pts = [(o.CPoint(k).x / 1e6, o.CPoint(k).y / 1e6)
                       for k in range(o.PointCount())]
                if len(pts) < 3:
                    continue
                g = Polygon(pts).buffer(0)
                if g.is_empty or g.area <= 0:
                    continue
                # SLIVER: erode by half the sliver limit; if the piece vanishes
                # it is everywhere thinner than the process can hold.
                if g.buffer(-r["sliver"] / 2.0).is_empty:
                    out["slivers"].append(
                        {"zone": nm, "net": net, "layer": pcbnew.LayerName(lid),
                         "area_mm2": round(g.area, 3),
                         "at": [round(g.centroid.x, 2), round(g.centroid.y, 2)]})
                # ISLAND: no pad, via or track of this net touches the piece
                touched = False
                for fp in b.GetFootprints():
                    for pd in fp.Pads():
                        if pd.GetNetname() != net or not pd.IsOnLayer(lid):
                            continue
                        pb = pd.GetBoundingBox()
                        if g.intersects(_box(pb.GetLeft() / 1e6, pb.GetTop() / 1e6,
                                             pb.GetRight() / 1e6, pb.GetBottom() / 1e6)):
                            touched = True
                            break
                    if touched:
                        break
                if not touched:
                    for t in b.GetTracks():
                        if t.GetNetname() != net:
                            continue
                        if t.GetClass() == "PCB_VIA" and t.IsOnLayer(lid):
                            p = t.GetPosition()
                            if g.intersects(_box(p.x / 1e6 - .3, p.y / 1e6 - .3,
                                                 p.x / 1e6 + .3, p.y / 1e6 + .3)):
                                touched = True
                                break
                        elif t.GetClass() == "PCB_TRACK" and t.GetLayer() == lid:
                            s_, e_ = t.GetStart(), t.GetEnd()
                            if g.intersects(LineString([(s_.x / 1e6, s_.y / 1e6),
                                                        (e_.x / 1e6, e_.y / 1e6)])):
                                touched = True
                                break
                if not touched and g.area > 0.05:
                    out["islands"].append(
                        {"zone": nm, "net": net, "layer": pcbnew.LayerName(lid),
                         "area_mm2": round(g.area, 3),
                         "at": [round(g.centroid.x, 2), round(g.centroid.y, 2)]})

    # --- acid traps: two connected tracks of one net meeting at an acute angle.
    # Etchant is held in the notch and keeps biting after the rest has cleared.
    import math
    ends = collections.defaultdict(list)
    for t in b.GetTracks():
        if t.GetClass() != "PCB_TRACK":
            continue
        s_, e_ = t.GetStart(), t.GetEnd()
        a = (round(s_.x / 1e6, 3), round(s_.y / 1e6, 3))
        c = (round(e_.x / 1e6, 3), round(e_.y / 1e6, 3))
        if a == c:
            continue
        ends[(a, t.GetLayer(), t.GetNetname())].append(c)
        ends[(c, t.GetLayer(), t.GetNetname())].append(a)
    for (pt, lid, net), others in ends.items():
        if len(others) != 2:
            continue
        (x1, y1), (x2, y2) = others[0], others[1]
        v1 = (x1 - pt[0], y1 - pt[1])
        v2 = (x2 - pt[0], y2 - pt[1])
        n1 = math.hypot(*v1)
        n2 = math.hypot(*v2)
        if n1 < 1e-6 or n2 < 1e-6:
            continue
        cosang = (v1[0] * v2[0] + v1[1] * v2[1]) / (n1 * n2)
        ang = math.degrees(math.acos(max(-1.0, min(1.0, cosang))))
        if ang < 60.0:                                     # industry rule of thumb
            out["acid_traps"].append(
                {"net": net, "layer": pcbnew.LayerName(lid),
                 "angle_deg": round(ang, 1), "at": [pt[0], pt[1]]})
    return out


def check(board_path, prof_key, copper_oz, do_artifacts=True):
    prof = PROFILES[prof_key]
    r = profile_rules(prof, copper_oz)
    viol, unconn = run_fab_drc(board_path, r)
    rep = {"board": os.path.relpath(board_path), "profile": prof["name"],
           "copper_oz": copper_oz, "rules": r}
    if viol is None:
        rep["error"] = "DRC did not produce a report"
        return rep
    rep["drc"] = dict(collections.Counter(v.get("type") for v in viol))
    rep["drc_total"] = len(viol)
    rep["unconnected"] = len(unconn)
    rep["examples"] = [v.get("description", "")[:110] for v in viol[:6]]
    if do_artifacts:
        try:
            rep.update(artifact_scan(board_path, r))
        except Exception as e:                             # noqa: BLE001
            rep["artifact_error"] = "%s: %s" % (type(e).__name__, e)
    return rep


def summarise(rep):
    if "error" in rep:
        return "%-46s ERROR %s" % (os.path.basename(rep["board"])[:46], rep["error"])
    n_s = len(rep.get("slivers", []))
    n_i = len(rep.get("islands", []))
    n_a = len(rep.get("acid_traps", []))
    blocking = rep["drc_total"] + n_s + n_i
    return ("%-46s fab_drc=%-4d unconn=%-4d slivers=%-3d islands=%-3d acid_traps=%-3d %s"
            % (os.path.basename(rep["board"])[:46], rep["drc_total"],
               rep["unconnected"], n_s, n_i, n_a,
               "FAB OK" if blocking == 0 else "BLOCKED"))


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("boards", nargs="+")
    ap.add_argument("--profile", default="jlcpcb", choices=sorted(PROFILES))
    ap.add_argument("--copper-oz", type=float, default=2.0,
                    help="outer copper weight; 2oz is the binding case here")
    ap.add_argument("--json", default="")
    ap.add_argument("--no-artifacts", action="store_true")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()
    reps, bad = [], 0
    for bp in a.boards:
        if not os.path.isfile(bp):
            print("MISSING %s" % bp)
            continue
        rep = check(bp, a.profile, a.copper_oz, not a.no_artifacts)
        reps.append(rep)
        print(summarise(rep), flush=True)
        if rep.get("drc_total", 0) or rep.get("slivers") or rep.get("islands"):
            bad += 1
        if not a.quiet:
            for k, n in sorted((rep.get("drc") or {}).items(), key=lambda kv: -kv[1]):
                print("      %-30s %d" % (k, n))
            for ex in rep.get("examples", [])[:3]:
                print("      %s" % ex)
            for s in (rep.get("slivers") or [])[:3]:
                print("      SLIVER %s [%s] %s %.3fmm2 at %s"
                      % (s["zone"], s["net"], s["layer"], s["area_mm2"], s["at"]))
            for s in (rep.get("islands") or [])[:3]:
                print("      ISLAND %s [%s] %s %.3fmm2 at %s"
                      % (s["zone"], s["net"], s["layer"], s["area_mm2"], s["at"]))
            for s in (rep.get("acid_traps") or [])[:2]:
                print("      ACID TRAP %s %s %.1fdeg at %s"
                      % (s["net"], s["layer"], s["angle_deg"], s["at"]))
    if a.json:
        with open(a.json, "w") as fh:
            json.dump(reps, fh, indent=1, default=str)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
